### ISSUE TITLE
Repo clean

### ISSUE THREAD

**Issue by wschoenell** [tribeiro/chimera-manager#3]
@tribeiro,

Can you clean this repo and move to @astroufsc organization? The tasks would be:

- [x] Clean the branches leaving only master
- [x] Rename this plugin to `chimera-supervisor`
- [x] Update documentation
- [x] Finally, move to @astroufsc

**Comment by tribeiro** [comment]
Ok! Most of these tasks are complete. Now, documentation will require a lot more work to be complete.
